### PR TITLE
Added fields emoji and forward_from_chat

### PR DESCRIPTION
**Pull request by anronin**
Recent changes in Bot API from May 6, 2016
https://core.telegram.org/bots/api#recent-changes

### CODE REVIEW

**Comment by anronin** [comment]
Can i ask you about `chat: User.t | GroupChat.t` in `Message` type spec? May be it should be replaced by `Chat.t`?

**Comment by zhyu** [comment]
oh you're right, it should be `chat: Chat.t`.
It seems I forgot to replace it.

**Comment by anronin** [comment]
a can replace it in this PR, ok?

**Comment by zhyu** [comment]
👌  go ahead.
thanks for pointing that out.

**Comment by anronin** [comment]
and it's ready to merge)

**Comment by zhyu** [comment]
Thx!

**Pull request merged**
