### PR TITLE
Implement inline queries feature

### PR DESCRIPTION
**Pull request by mendab1e**
https://github.com/zhyu/nadia/issues/4 Support for [Inline bot requests](https://core.telegram.org/bots/inline) has been implemented in this PR.

### CODE REVIEW

**Comment by mendab1e** [comment]
@zhyu what do you think about extraction of InlineQueryResults from Model to a separate structure?

**Comment by zhyu** [comment]
> @zhyu what do you think about extraction of InlineQueryResults from Model to a separate structure?

good idea!
maybe we can move them to `Model.InlineQueryResult`

**Comment by mendab1e** [comment]
Ok, i've moved them.

**Comment by mendab1e** [comment]
@zhyu ok, done.

**Comment by mendab1e** [comment]
Yes, I forgot about `options`. Fixed.

**Comment by zhyu** [comment]
LGTM!

**Pull request merged**
