### PR TITLE
Allow base url to be configurable for both the normal and graph api

### LINKED ISSUE #41: Configurable API-Endpoint
Since i'm not only new to Elixir, but to Telegram as well - i was trying to proxy every request (inbound to my server as well as outbound to telegrams server). For their webhooks that worked pretty well, because you can put in every url you like as long as its https.

i wasn't able to make it work for/with Nadia, since the API-Endpoint is hardcoded in `lib/nadia/api.ex`.

i'm guessing that switching the API-Endpoint isn't a thing that is often done (completely understandable) but i still think it's a good idea to have that option. especially in the beginning when you start to make requests, it would be helpful if the requests could be send to any http endpoint .. so one would be able to verify what he/she is actually trying to send out :)

not yet sure about the tests for this, but the idea would probably be make it work the same way as `config_or_env` is already doing its job for the token.

I'll try to come up with a PR, depending on how much time there is .. somewhere in the next weeks.

WDYT @zhyu?

### PR DESCRIPTION
**Pull request by dotboris**
Fixes #41 

Ask and you shall receive (give or take 10 months).

### CODE REVIEW

**Comment by dotboris** [comment]
Right now, I've tested this by hand and it works fine but I'm not really satisfied by lack of tests. If you look closely you can see that the config loading code is copied from `api.ex` to `graph/api.ex`. Sounds like a perfect target for extraction.

**Comment by dotboris** [comment]
While extracting a `Nadia.Config` module to handle reading the config would be nice. I'm not sure how to test it. In order for me to test it properly I would need to set the config dynamically and I'm not sure how to do that. Does anybody have any pointers?

**Comment by dotboris** [comment]
Looks like I could use [`Application.put_env/4`](https://hexdocs.pm/elixir/1.5.1/Application.html#put_env/4) but the `:timeout` option scares me. I'm not sure what it really does. It seems like it could affect the `.app` file instead of changing the configuration at runtime.

**Comment by dotboris** [comment]
I've extracted a `Nadia.Config` module and I've test both the `base_url/0` and `graph_base_url/0` methods that I've added.

**Comment by amitizle** [comment]
Nice! I hope it gets merged soon

**Comment by zhyu** [comment]
Cool!
I'm sorry for keeping you waiting 😭

**Pull request merged**
