### PR TITLE
Added deleteMessage support

### PR DESCRIPTION
**Pull request by m1ome**
Docs: https://core.telegram.org/bots/api#deletemessage

### CODE REVIEW

**Comment by zhyu** [comment]
Thanks for you p-r.

Could you please add the document of `delete_message` like other functions?

**Comment by m1ome** [comment]
@zhyu can you please check?

**Comment by zhyu** [comment]
merged. Thanks!

**Comment by m1ome** [comment]
@zhyu you are welcome

**Comment by m1ome** [comment]
thanks for a great lib, btw!

**Pull request merged**
