### PR TITLE
Add support for Bot API 2.1

### PR DESCRIPTION
**Pull request by anronin**
closes https://github.com/zhyu/nadia/issues/31

Since all new methods only for group managing still don't know how to properly test this

EDIT: I mean, how to add tests. so I'm testing it with my bot)

EDIT2: give me some time, i guess i can do tests)

### CODE REVIEW

**Comment by anronin** [comment]
i think i've done tests correctly, tell me if i'm wrong

**Comment by zhyu** [comment]
I'm sorry, I'm a little busy this week. But I'll review the code in the weekend.
It seems you test it well 👍

**Comment by anronin** [comment]
no problem, take your time) 
i will try to do tests for Bot API 2.0 methods for now

**Comment by zhyu** [comment]
Good work! Thanks! 👍

**Pull request merged**
