### PR TITLE
use with from elixir 1.2

### PR DESCRIPTION
**Pull request by anronin**
My naive implementation of 'with' feature from elixir 1.2, please tell me if it awful, and i'll go away to learn more elixir ;)

### CODE REVIEW

**Comment by anronin** [comment]
I'll do better when "with" in elixir got else conditions and guards, now it's in elixir master

**Comment by zhyu** [comment]
Good implementation! :+1: 

But I'd like to change the method name, since I can't understand what this method will do when I saw `process_within` only.
IMO, a method name should show the main thing it will do.
So, maybe it's better to change it to `decode_response` or other better names you can think up.

**Comment by anronin** [comment]
Yeah, sorry forgot about function name. And since I just started to learn elixir and programming, can you tell me what name to choose:

**Comment by anronin** [comment]
Yeah, sorry forgot about function name. And since I just started to learn elixir and programming, can you tell me what name to choose:

**Comment by anronin** [comment]
Yeah, sorry forgot about function name. And since I just started to learn elixir and programming, can you tell me what name to choose:

1. process_response/1 (since it has a single argument that can be called just like a function with two arguments, as I understand it)
2. do_process_response/1 (since this function is that the kind of helper and I've seen it in someone else's code) or your version
3. decode_response/1 (as it is your code and your rules and i like it too)

**Comment by zhyu** [comment]
IMO, pattern matching in function definitions is something like `case`, we can have two functions with the same name, and we will call one of them based on arguments.
Since this function is not at the same level with `process_response/2`, I don't vote for `process_response/1`.

Both `do_process_response/1` and `decode_response/1` are great. I prefer to choose `decode_response/1` just in my interest. :)

**Comment by anronin** [comment]
ok, thank you for helping to select a name, it is always a difficult task ;)

**Comment by zhyu** [comment]
Thanks for the tough work!
Anyway, it's better to make the commit message more meaningful. e.g. 'change the function name...' for the last commit.

**Comment by anronin** [comment]
ok, it's just too new to me. I understood, the next time commit messages will be more meaningful

**Comment by zhyu** [comment]
:+1: 
actually, if you like, you can also change the commit messages you've already pushed.
FYI, http://stackoverflow.com/questions/179123/edit-an-incorrect-commit-message-in-git

**Comment by anronin** [comment]
oops, sorry( is it okay, or do I have to do something to fix it?

**Comment by anronin** [comment]
I can change last commit message again, but the right way this time?

**Comment by anronin** [comment]
and it works. errors help to learn)

**Comment by zhyu** [comment]
You can also change the commit message which isn't the recent one using `git rebase --interactive <sha1-commit-id>`.

It's so powerful, and maybe you'd like to try it.

**Comment by anronin** [comment]
cool, tnx. need learn more git.

**Comment by zhyu** [comment]
Great works!
:100: :ok_hand:

**Pull request merged**
